# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [6]:
string="hi there sam!"
print(string.split())

['hi', 'there', 'sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [7]:
txt="the diameter of earth is{diameter:}kilometer"
print(txt.format(diameter=12742))

the diameter of earth is12742kilometer

In [ ]:
rget

## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

## 5. Create an array of all the even integers from 20 to 35

In [15]:
import numpy as np
array=np.arange(20,36,2)
print("array of all the even integers from 20to 35")
print(array)

array of all the even integers from 20to 35
[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [29]:
import numpy as np 
x=np.arange(0,9).reshape(3,3) 
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [30]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd

In [35]:
import pandas as pd
data=[[1,0],[2,3],[4,5]]
df=pd.DataFrame(data)
df

   0  1
0  1  0
1  2  3
2  4  5

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [43]:
ser=pd.date_range(start='1-1-2023',end='2-10-2023')
for val in ser:
  print(val)

2023-01-01 00:00:00
2023-01-02 00:00:00
2023-01-03 00:00:00
2023-01-04 00:00:00
2023-01-05 00:00:00
2023-01-06 00:00:00
2023-01-07 00:00:00
2023-01-08 00:00:00
2023-01-09 00:00:00
2023-01-10 00:00:00
2023-01-11 00:00:00
2023-01-12 00:00:00
2023-01-13 00:00:00
2023-01-14 00:00:00
2023-01-15 00:00:00
2023-01-16 00:00:00
2023-01-17 00:00:00
2023-01-18 00:00:00
2023-01-19 00:00:00
2023-01-20 00:00:00
2023-01-21 00:00:00
2023-01-22 00:00:00
2023-01-23 00:00:00
2023-01-24 00:00:00
2023-01-25 00:00:00
2023-01-26 00:00:00
2023-01-27 00:00:00
2023-01-28 00:00:00
2023-01-29 00:00:00
2023-01-30 00:00:00
2023-01-31 00:00:00
2023-02-01 00:00:00
2023-02-02 00:00:00
2023-02-03 00:00:00
2023-02-04 00:00:00
2023-02-05 00:00:00
2023-02-06 00:00:00
2023-02-07 00:00:00
2023-02-08 00:00:00
2023-02-09 00:00:00
2023-02-10 00:00:00

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [39]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists) 
df

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24

SyntaxError: ignored